precision highp float;
attribute vec3 a_position;
attribute vec3 a_normal;
varying vec3 v_normal;
attribute vec4 a_joint;
attribute vec4 a_weight;
uniform mat4 u_jointMat[62];
uniform mat3 u_normalMatrix;
uniform mat4 u_modelViewMatrix;
uniform mat4 u_projectionMatrix;
attribute vec2 a_texcoord0;
varying vec2 v_texcoord0;
varying vec3 v_light0Direction;
varying vec3 v_position;
uniform mat4 u_light0Transform;
varying vec3 v_light1Direction;
uniform mat4 u_light1Transform;
varying vec3 v_light2Direction;
uniform mat4 u_light2Transform;
varying vec3 v_light3Direction;
uniform mat4 u_light3Transform;
varying vec3 v_light4Direction;
uniform mat4 u_light4Transform;
varying vec3 v_light5Direction;
uniform mat4 u_light5Transform;
void main(void) {
mat4 skinMat = a_weight.x * u_jointMat[int(a_joint.x)];
skinMat += a_weight.y * u_jointMat[int(a_joint.y)];
skinMat += a_weight.z * u_jointMat[int(a_joint.z)];
skinMat += a_weight.w * u_jointMat[int(a_joint.w)];
vec4 pos = u_modelViewMatrix * skinMat * vec4(a_position,1.0);
v_normal = u_normalMatrix * mat3(skinMat)* a_normal;
v_texcoord0 = a_texcoord0;
v_position = pos.xyz;
v_light0Direction = mat3(u_light0Transform) * vec3(0.,0.,1.);
v_light1Direction = u_light1Transform[3].xyz - pos.xyz;
v_light2Direction = u_light2Transform[3].xyz - pos.xyz;
v_light3Direction = u_light3Transform[3].xyz - pos.xyz;
v_light4Direction = u_light4Transform[3].xyz - pos.xyz;
v_light5Direction = u_light5Transform[3].xyz - pos.xyz;
gl_Position = u_projectionMatrix * pos;
}
